# Generated by Django 4.2.16 on 2024-09-18 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_moodentry_kelas_moodentry_name_moodentry_npm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodentry',
            old_name='name',
            new_name='nama',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
